### ISSUE TITLE
Hilbert transform?

### ISSUE THREAD

**Issue by ghost** [jaidevd/pyhht#10]
Hi! I'm also writing a HHT implementation in Julia, as part of an article. Have you found any decent and clear implementations of the Hilbert transform?

https://github.com/nutschig/hilbert-huang-transform

**Comment by jaidevd** [comment]
Hi Nick,

The Hilbert transform implementation that I've used comes with the standard
SciPy library.

BTW, what article is this? Would it be possible for you to make it
available?

**Comment by jaidevd** [comment]
@nutschig 

After going through the Julia docs, it seems like Julia doesn't have a Hilbert transform at all. However, I've seen the source code of the Hilbert transform in SciPy, and it seems straightforward enough to implement. I'll give it a shot and let you know.

**Comment by jaidevd** [comment]
@nutschig I've tried to make a crude Hilbert implementation in Julia based on SciPy. You can see it here - https://github.com/jaidevd/hht.jl/blob/master/hht.jl

With this, you can perform a Hilbert transform as follows:

``` julia
x = linspace(0, 2*pi, 1000);
y = sin(x);
using hht
z = hilbert(y)
using PyPlot
plot(real(z), imag(z))
xlim(-1, 1)
ylim(-1, 1)
```

This produces the following plot - 
![figure_1](https://cloud.githubusercontent.com/assets/1250388/8148213/f0cc8d62-12ae-11e5-99ff-7e0e6187d01f.png)

**Comment by ghost** [comment]
@jaidevd

Jaidev,

Thank you! The article is just a jupyter notebook that I'll post to Hacker News. I'm developing it at https://github.com/nutschig/hilbert-huang-transform , and I'll credit you for the Hilbert transform! I just found the Fourier transform equations yesterday on the "Analytic signal" wiki article.
