### ISSUE TITLE
stop_sifting(m) and 'fixe' problem

### ISSUE THREAD

**Issue by oxsem** [jaidevd/pyhht#31]
Hello,

whenever I'm trying to set fixed number of sifting ('fixe' parameter) OR when checking the stopping criteria for the current mode I get:
**TypeError: mean_and_amplitude() takes exactly 2 arguments (1 given)**

although I don't understands what am I doing wrong:

decomp_data = pyhht.emd.EMD(np.asarray(data))
decomp_data.stop_sifting(np.asarray(data))
OR
decomp_data = pyhht.emd.EMD(np.asarray(data), fixe=9)
decomp_data.decompose()

Could you please advice? Thank you!

**Comment by jaidevd** [comment]
Hi @oxsem,

Thanks for reporting this. Seems like a minor bug, but unfortunately I'm traveling right now and will be back on Monday. Will take a look at this soon after.

Thanks again .

**Comment by oxsem** [comment]
Hello,
I wonder if there is any update on the issue above?
Thanks!

**Comment by jaidevd** [comment]
Hi @oxsem,

Sorry, been somewhat busy at work. Give me till the weekend and I'll get this fixed.

Thanks.

**Comment by jaidevd** [comment]
Hi @oxsem 
Please pull from the latest update on the master branch, this should be fixed now. Thanks
