### ISSUE TITLE
how to produce more imfs?

### ISSUE THREAD

**Issue by maihao14** [jaidevd/pyhht#38]
I try some seismic signal use this EMD  cannot yield same imfs solution as  emd in MATLAB 
and I do not know why ?
Why this emd tool usually only produce 2 imfs component but emd in MATLAB can produce 8~9 imfs?

**Comment by jaidevd** [comment]
This could either be a bug in pyhht, or there could be something wrong in the way in which you are using the EMD class. Can you show how you have used it?

**Comment by maihao14** [comment]
Code：
        decom = EMD(x)
        imfs = decom.decompose()

x is a matrix length 4501 and  run no problem in Matlab emd
and in  pyhht  it can not yield the same size imfs group as I expect  
actually it can only produce 2 imfs or directly send error:
/Users/maihao/anaconda/lib/python3.6/site-packages/pyhht-0.0.1-py3.6.egg/pyhht/emd.py:292: RuntimeWarning: invalid value encountered in greater

**Comment by jaidevd** [comment]
Can you try the following:
```python
decom = EMD(x, n_imfs=8)
imfs = decom.decompose()
```
And tell me what happens?

**Comment by maihao14** [comment]
run console send:
/Users/maihao/anaconda/lib/python3.6/site-packages/pyhht-0.0.1-py3.6.egg/pyhht/emd.py:292: RuntimeWarning: invalid value encountered in greater
/Users/maihao/anaconda/lib/python3.6/site-packages/pyhht-0.0.1-py3.6.egg/pyhht/emd.py:293: RuntimeWarning: invalid value encountered in greater
/Users/maihao/anaconda/lib/python3.6/site-packages/pyhht-0.0.1-py3.6.egg/pyhht/utils.py:235: RuntimeWarning: invalid value encountered in less
/Users/maihao/anaconda/lib/python3.6/site-packages/scipy/signal/_peak_finding.py:68: RuntimeWarning: invalid value encountered in greater
  results &= comparator(main, plus)
/Users/maihao/anaconda/lib/python3.6/site-packages/scipy/signal/_peak_finding.py:69: RuntimeWarning: invalid value encountered in greater
  results &= comparator(main, minus)
/Users/maihao/anaconda/lib/python3.6/site-packages/scipy/signal/_peak_finding.py:68: RuntimeWarning: invalid value encountered in less
  results &= comparator(main, plus)
/Users/maihao/anaconda/lib/python3.6/site-packages/scipy/signal/_peak_finding.py:69: RuntimeWarning: invalid value encountered in less
  results &= comparator(main, minus)

and the variable explorer shows 
imfs only has size 2

**Comment by maihao14** [comment]
and it's strange that  I have 30 different series samples of x (seismic data)  
some of them  can run correctly and have 8 imfs  components but others cannot
In Matlab emd all of them work successfully 
and I noticed that  the imfs I get  between emd in Matlab and  pyhht seem not the same

**Comment by jaidevd** [comment]
Okay, this seems to be a bug. Can you share some of the samples that are
showing incorrect number of IMFs?

**Comment by maihao14** [comment]
OK Thanks  I will send sample data to your email later

**Comment by jaidevd** [comment]
Hi @maihao14 
I checked with the samples you sent, and it seems to be working fine. Here are the IMFs I'm getting for data1.npy and data2.npy respectively.

`data1.npy`
![data1](https://user-images.githubusercontent.com/1250388/29411708-9d0eab5a-8373-11e7-9415-1a9e6bb92618.png)
`data2.npy`
![data2](https://user-images.githubusercontent.com/1250388/29411711-9f4c0af2-8373-11e7-842c-33b83ef857fd.png)

I need some more help to understand why this is not working for you. How did you install pyhht? Please download latest "dev" branch from GitHub and install it using the following:
```bash
$ python setup.py install
```
and try the decomposition again. If it still doesn't work, then we will need to dig further.
Thanks

**Comment by maihao14** [comment]
I use git clone to update pyhht and then test all 30 samples 
all of them working !!! 
Thank you for your help!  I guess maybe I get older version of pyhht  via  conda install pyhht
Thanks again and best wishes!
