### ISSUE TITLE
more detailed ref to paper

### ISSUE THREAD

**Issue by ggrrll** [jaidevd/pyhht#54]
https://github.com/jaidevd/pyhht/blob/b5e15b9fb372dc1a97fa87e9d828c8f2c6597700/pyhht/emd.py#L32

Hi, 

sorry, trivial question -- I cannot find the theta1, theta2, alpha pars in the original paper (attached hereby)
Could you point to them?  ( In particular I  was expecting them in section 5...)

Thanks again
[HHT_original.pdf](https://github.com/jaidevd/pyhht/files/2306853/HHT_original.pdf)

**Comment by jaidevd** [comment]
Hi @ggrrll 

Sorry, my bad. Those parameters are from this paper: http://perso.ens-lyon.fr/patrick.flandrin/NSIP03.pdf

I wrote the docstring incorrectly.

Fixed in https://github.com/jaidevd/pyhht/commit/8ab0dd8880f5d19130e044dd9bb596223bd05c8e

**Comment by ggrrll** [comment]
Thanks! 

are these changes (with fixes from other issues) automatically updated on pip repo?

**Comment by jaidevd** [comment]
@ggrrll 

No, the package has to be periodically uploaded to PyPI whenever we make a release. There must be an automated way to do this, of course. I'll investigate that sometime. I'm anticipating a stable release around early November.

**Comment by ggrrll** [comment]
hi, 

only now I had time to check the paper... the `ref [4]`  [](https://pyhht.readthedocs.io/en/latest/apiref/pyhht.html#pyhht.emd.EmpiricalModeDecompositionl) is actually to this paper

https://hal-ens-lyon.archives-ouvertes.fr/file/index/docid/137611/filename/manuscript.pdf
where there is also no sign of `theta_1`, `theta_2`, `alpha` ...

I guess you should change the ref in the docs...

**Comment by jaidevd** [comment]
Arghh.. never write documentation when overworked. Fixed, thanks!
