### ISSUE TITLE
problem with emd function in EMD.py. 

### ISSUE THREAD

**Issue by jasonji84** [jaidevd/pyhht#6]
When the size of data is even number, emd function can run correctly. If the size is odd number, the emd function cannot  run.  I run the default configure.
 
Here are the error information
 
signals[0:base / 2, 0] = data[::-1][base / 2:]
ValueError: could not broadcast input array from shape (2039) into shape (2038)

By the way, I test the matlab emd, which can handle any size of data.

**Comment by jaidevd** [comment]
Thanks for pointing this out. I'll look into it.

**Comment by jaidevd** [comment]
@jasonji84 The latest implementation of the EMD class solves this issue. Please check it out. You can use it as follows:

``` python
from pyhht.emd import EMD
emd = EMD(input_signal)
imfs = emd.decompose()
```
