### ISSUE TITLE
why this pyhht.emd diffrent with matlab 2018a emd result!

### ISSUE THREAD

**Issue by monster-xie** [jaidevd/pyhht#64]
from pyhht.emd import EMD
decomposer = EMD(data[0])
imf = decomposer.decompose()

matlab code is :
emd(data(1,:))

**Comment by jaidevd** [comment]
Hi @monster-xie 

Can you share more details? What is the ideal output you are expecting, and what is the output you are getting?

Thanks,

**Comment by monster-xie** [comment]
> Hi @monster-xie
> 
> Can you share more details? What is the ideal output you are expecting, and what is the output you are getting?
> 
> Thanks,

the raw data is :
![image](https://user-images.githubusercontent.com/5821515/70860007-ec47d300-1f56-11ea-9c09-429b4ba27917.png)

and use pyhht.emd imf data is :
![image](https://user-images.githubusercontent.com/5821515/70860018-19948100-1f57-11ea-83ae-86bf6ee27ca0.png)

the matlab imf data is :
![image](https://user-images.githubusercontent.com/5821515/70860037-5b252c00-1f57-11ea-8e1e-7a2b51c3cc35.png)

**Comment by jaidevd** [comment]
Thanks, @monster-xie 

We cannot guarantee exact numerical reproduction of the data, since this package is not a line by line reproduction of the MATLAB package. Can you plot the IMFs in the two implementations and compare them?

**Comment by monster-xie** [comment]
> Thanks, @monster-xie
> 
> We cannot guarantee exact numerical reproduction of the data, since this package is not a line by line reproduction of the MATLAB package. Can you plot the IMFs in the two implementations and compare them?

thanks, @jaidevd 
I just want to know ,this pyhht.emd is correct implemention the emd algorithm?

**Comment by jaidevd** [comment]
Yes.
